# Auto-generated object type map from otypes.list
OBJECT_TYPE_MAP = {
    '*': 'Star',
    '**': 'Double or Multiple Star',
    'AB*': 'Asymptotic Giant Branch Star',
    'AGN': 'Active Galaxy Nucleus',
    'Ae*': 'Herbig Ae/Be Star',
    'As*': 'Association of Stars',
    'BD*': 'Brown Dwarf',
    'BLL': 'BL Lac',
    'BS*': 'Blue Straggler',
    'BY*': 'BY Dra Variable',
    'Be*': 'Be Star',
    'BiC': 'Brightest Galaxy in a Cluster (BCG)',
    'Bla': 'Blazar',
    'C*': 'Carbon Star',
    'CGG': 'Compact Group of Galaxies',
    'CGb': 'Cometary Globule / Pillar',
    'CV*': 'Cataclysmic Binary',
    'Ce*': 'Cepheid Variable',
    'Cl*': 'Cluster of Stars',
    'ClG': 'Cluster of Galaxies',
    'Cld': 'Cloud',
    'DNe': 'Dark Cloud (nebula)',
    'EB*': 'Eclipsing Binary',
    'El*': 'Ellipsoidal Variable',
    'Em*': 'Emission-line Star',
    'EmG': 'Emission-line galaxy',
    'Er*': 'Eruptive Variable',
    'Ev*': 'Evolved Star',
    'G': 'Galaxy',
    'GNe': 'Nebula',
    'GiC': 'Galaxy towards a Cluster of Galaxies',
    'GiG': 'Galaxy towards a Group of Galaxies',
    'GiP': 'Galaxy in Pair of Galaxies',
    'GlC': 'Globular Cluster',
    'GrG': 'Group of Galaxies',
    'H2G': 'HII Galaxy',
    'HB*': 'Horizontal Branch Star',
    'HH': 'Herbig-Haro Object',
    'HII': 'HII Region',
    'HS*': 'Hot Subdwarf',
    'HV*': 'High Velocity Star',
    'HVC': 'High-velocity Cloud',
    'HXB': 'High Mass X-ray Binary',
    'IG': 'Interacting Galaxies',
    'ISM': 'Interstellar Medium Object',
    'Ir*': 'Irregular Variable',
    'LIN': 'LINER-type Active Galaxy Nucleus',
    'LM*': 'Low-mass Star',
    'LP*': 'Long-Period Variable',
    'LSB': 'Low Surface Brightness Galaxy',
    'LXB': 'Low Mass X-ray Binary',
    'MGr': 'Moving Group',
    'MS*': 'Main Sequence Star',
    'Ma*': 'Massive Star',
    'Mi*': 'Mira Variable',
    'MoC': 'Molecular Cloud',
    'N*': 'Neutron Star',
    'No*': 'Classical Nova',
    'OH*': 'OH/IR Star',
    'OpC': 'Open Cluster',
    'Or*': 'Orion Variable',
    'PCG': 'Proto Cluster of Galaxies',
    'PM*': 'High Proper Motion Star',
    'PN': 'Planetary Nebula',
    'PaG': 'Pair of Galaxies',
    'Pe*': 'Chemically Peculiar Star',
    'Pl': 'Extra-solar Planet',
    'Psr': 'Pulsar',
    'Pu*': 'Pulsating Variable',
    'QSO': 'Quasar',
    'RC*': 'R CrB Variable',
    'RG*': 'Red Giant Branch star',
    'RNe': 'Reflection Nebula',
    'RR*': 'RR Lyrae Variable',
    'RS*': 'RS CVn Variable',
    'RV*': 'RV Tauri Variable',
    'Ro*': 'Rotating Variable',
    'S*': 'S Star',
    'SB*': 'Spectroscopic Binary',
    'SBG': 'Starburst Galaxy',
    'SCG': 'Supercluster of Galaxies',
    'SFR': 'Star Forming Region',
    'SN*': 'SuperNova',
    'SNR': 'SuperNova Remnant',
    'SX*': 'SX Phe Variable',
    'St*': 'Stellar Stream',
    'Sy*': 'Symbiotic Star',
    'Sy1': 'Seyfert 1 Galaxy',
    'Sy2': 'Seyfert 2 Galaxy',
    'SyG': 'Seyfert Galaxy',
    'TT*': 'T Tauri Star',
    'V*': 'Variable Star',
    'WD*': 'White Dwarf',
    'WR*': 'Wolf-Rayet',
    'WV*': 'Type II Cepheid Variable',
    'XB*': 'X-ray Binary',
    'Y*O': 'Young Stellar Object',
    'a2*': 'alpha2 CVn Variable',
    'bC*': 'beta Cep Variable',
    'bCG': 'Blue Compact Galaxy',
    'bub': 'Bubble',
    'cC*': 'Classical Cepheid Variable',
    'cor': 'Dense Core',
    'dS*': 'delta Sct Variable',
    'flt': 'Interstellar Filament',
    'gD*': 'gamma Dor Variable',
    'glb': 'Globule (low-mass dark cloud)',
    'out': 'Outflow',
    'pA*': 'Post-AGB Star',
    'rG': 'Radio Galaxy',
    's*b': 'Blue Supergiant',
    's*r': 'Red Supergiant',
    's*y': 'Yellow Supergiant',
    'sg*': 'Evolved Supergiant',
    'sh': 'Interstellar Shell',
    'vid': 'Underdense Region of the Universe',
}
